import { GetUpcomingUsecase } from "../../application/usecase/task/upComming.usecase";

export const TYPES = {
  DatabaseType: Symbol.for("DatabaseClient"),
  MessageQueue:Symbol.for("MessageQueue"),
  Publisher:Symbol.for("Publisher"),
  Consumer:Symbol.for("Consumer"),
  UnitWork:Symbol.for("UnitWork"),
  Cache:Symbol.for("Cache"),
  CheckOwnerTagUsecase:Symbol.for("CheckOwnerTagUsecase"),
  WorkSpaceUsecase:Symbol.for("WorkSpaceUsecase"),

  GetProfileUsecase:Symbol.for("GetProfileUsecase"),
  GetTodayUsecase:Symbol.for("GetTodayUsecase"),
  GetUpcomingUsecase:Symbol.for("GetUpcomingUsecase"),
  MemberRepository:Symbol.for("MemberRepository"),
  CheckPermissionListUsecase:Symbol.for("CheckPermissionListUsecase"),
  CheckPermissionTaskUsecase:Symbol.for("CheckPermissionTaskUsecase"),
  CheckPermissionSectionUsecase:Symbol.for("CheckPermissionSectionUsecase"),
  InviteMemberUsecase:Symbol.for("InviteMemberUsecase"),
  SearchMemberUsecase:Symbol.for("SearchMemberUsecase"),
  DeleteMemberUsecase:Symbol.for("DeleteMemberUsecase"),
  ChangeRoleUsecase:Symbol.for("ChangeRoleUsecase"),
  StatusInviteUsecase:Symbol.for("StatusInviteUsecase"),

  ListRepository: Symbol.for("ListRepository"),
  GetAllListUsecase: Symbol.for("GetAllListUsecase"),
  GetListByIdUsecase: Symbol.for("GetListByIdUsecase"),
  CreateListUsecase: Symbol.for("CreateListUsecase"),
  UpdateListUsecase: Symbol.for("UpdateListUsecase"),
  DeleteListUsecase: Symbol.for("DeleteListUsecase"),
  CheckOwnerUsecase: Symbol.for("CheckOwnerUsecase"),
  InitListUsecase:Symbol.for("InitListUsecase"),
  SortSectionUsecase:Symbol.for("SortSectionUsecase"),
  GetAllListSectionUsecase:Symbol.for("GetAllListSectionUsecase"),


  GetInboxUsecase:Symbol.for("GetInboxUsecase"),

  TaskRepository: Symbol.for("TaskRepository"),
  GetAllTaskUsecase: Symbol.for("GetAllTaskUsecase"),
  GetTaskByIdUsecase: Symbol.for("GetTaskByIdUsecase"),
  CreateTaskUsecase: Symbol.for("CreateTaskUsecase"),
  CreateTaskWithSectionUsecase: Symbol.for("CreateTaskWithSectionUsecase"),
  UpdateTaskUsecase: Symbol.for("UpdateTaskUsecase"),
  DeleteTaskUsecase: Symbol.for("DeleteTaskUsecase"),
  updateTaskStatusUsecase:Symbol.for("UpdateTaskCompleteUsecase"),
  MoveToSectionUsecase:Symbol.for("MoveToSectionUsecase"),

  RuleRepository: Symbol.for("RuleRepository"),
  GetAllRuleUsecase: Symbol.for("GetAllRuleUsecase"),
  GetRuleByIdUsecase: Symbol.for("GetRuleByIdUsecase"),
  CreateRuleUsecase: Symbol.for("CreateRuleUsecase"),
  UpdateRuleUsecase: Symbol.for("UpdateRuleUsecase"),
  DeleteRuleUsecase: Symbol.for("DeleteRuleUsecase"),

  SectionRepository: Symbol.for("SectionRepository"),
  GetAllSectionUsecase: Symbol.for("GetAllSectionUsecase"),
  ChangePositionSectionUsecase:Symbol.for("ChangePositionSectionUsecase"),
  GetSectionByIdUsecase: Symbol.for("GetSectionByIdUsecase"),
  CreateSectionUsecase: Symbol.for("CreateSectionUsecase"),
  UpdateSectionUsecase: Symbol.for("UpdateSectionUsecase"),
  DeleteSectionUsecase: Symbol.for("DeleteSectionUsecase"),

  TagRepository: Symbol.for("TagRepository"),
  GetAllTagUsecase: Symbol.for("GetAllTagUsecase"),
  GetTagByIdUsecase: Symbol.for("GetTagByIdUsecase"),
  CreateTagUsecase: Symbol.for("CreateTagUsecase"),
  UpdateTagUsecase: Symbol.for("UpdateTagUsecase"),
  UpdateTagOnlyMeUsecase:Symbol.for("UpdateTagOnlyMeUsecase"),
  DeleteTagUsecase: Symbol.for("DeleteTagUsecase"),
  DeleteTagOnlyMeUsecase:Symbol.for("DeleteTagOnlyMeUsecase"),
  SynsMemberTagUsecase:Symbol.for("SynsMemberTagUsecase"),
  AddTagsForMemberUsecase:Symbol.for("AddTagsForMemberUsecase"),


  FilterRepository: Symbol.for("FilterRepository"),
  GetAllFilterUsecase: Symbol.for("GetAllFilterUsecase"),
  GetFilterByIdUsecase: Symbol.for("GetFilterByIdUsecase"),
  CreateFilterUsecase: Symbol.for("CreateFilterUsecase"),
  UpdateFilterUsecase: Symbol.for("UpdateFilterUsecase"),
  DeleteFilterUsecase: Symbol.for("DeleteFilterUsecase"),
  UpdateTagsInFilterUsecase:Symbol.for("UpdateTagsInFilterUsecase"),

  UserRepository:Symbol.for("UserRepository"),
  RegisterEmailUsecase:Symbol.for("RegisterUserCase"),
  ResetPasswordUsecase:Symbol.for("ResetPasswordUsecase"),
  LoginWithEmailUseCase:Symbol.for("LoginWithEmailUsecase"),
  SendResetPasswordUsecase:Symbol.for("SendResetPasswordUsecase"),
  SendOtpUsecase:Symbol.for("SendOtpUsecase"),
  ConfirmOtpUsecase:Symbol.for("ConfirmOtpUsecase"),
  RefreshUsecase:Symbol.for("RefreshTokenUseCase"),
  
  calculateDeadLineService:Symbol.for("calculateDeadLineService"),
  HashService:Symbol.for("HashService"),
  TokenService:Symbol.for("TokenService"),
  OtpService:Symbol.for("OtpService"),
  QueryFilterParserService:Symbol.for("QueryFilterParserService"),

  TagMapper:Symbol.for("TagMapper"),
  UserMapper:Symbol.for("UserMapper"),
  RuleMapper:Symbol.for("RuleMapper"),
  SectionMapper:Symbol.for("SectionMapper"),
  MemberMapper:Symbol.for("MemberMapper"),
  ListMapper:Symbol.for("ListMapper"),
  FilterMapper:Symbol.for("FilterMapper"),
  TaskMapper:Symbol.for("TaskMapper")
};
